name: CI-CD learn basic

on:
  push:
    branches:
      - change_to_mysql

jobs:
  build: 
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code Notification.
        uses: actions/checkout@v2
      
      - name: Setup .Net 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build App
        run: dotnet build -c Release --no-restore
      
      - name: Run automated test
        run: dotnet test -c Release --no-build